### ISSUE TITLE
Force refresh furigana

### ISSUE THREAD

**Issue by alamodey** [lingochamp/FuriganaTextView#11]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/55496019/115249524-03f72300-a16c-11eb-9a55-c80feef4dcbb.png">
I have managed to get FuriganaTextView to work in my flashcard app, which is great.

But I noticed in various scenarios, the furigana doesn't load immediately, and I have to switch to another tab and back to the first tab so that the furigana will draw. Is there a command after I set furiganaTextView.furiganas = furiganaArray to force the view to redraw the furigana? I tried furiganaTextView.setNeedsDisplay() without much luck. Thanks!

**Comment by eyeplum** [comment]
Congrats :) Also the app looks pretty neat.

I think making sure the furiganas are set before the contents are set would do the trick (see [here](https://github.com/lingochamp/FuriganaTextView/blob/03dc734c384cf50b1368607d3ab3c593ff8caedc/src/FuriganaTextView.swift#L34)). Sorry I no longer have the setup to run the repo so can't test it out for you.
