### ISSUE TITLE
有OC版本的吗

### ISSUE THREAD

**Issue by chenyun120** [lingochamp/FuriganaTextView#9]
有OC版本的吗

**Comment by eyeplum** [comment]
当时写这个控件是因为 `CoreText` 的 `CTRubyAnnotation` 需要 iOS 8 以上（当时项目需要支持 iOS 7），感觉现在只支持 iOS 8 以上应该已经不是问题了？如果可以的话推荐用 `CTRubyAnnotation`。

如果实在想用的话可以直接用 Xcode 生成的 Objective-C Header。

**Comment by chenyun120** [comment]
好的，谢谢，在弄日语的App，搞的头疼，不知道怎么写….


 原始邮件 
发件人: Yan Li<notifications@github.com>
收件人: lingochamp/FuriganaTextView<FuriganaTextView@noreply.github.com>
抄送: CY<chenyun120@126.com>; Author<author@noreply.github.com>
发送时间: 2020年8月24日(周一) 18:38
主题: Re: [lingochamp/FuriganaTextView] 有OC版本的吗 (#9)


当时写这个控件是因为 CoreText 的 CTRubyAnnotation 需要 iOS 8 以上（当时项目需要支持 iOS 7），感觉现在只支持 iOS 8 以上应该已经不是问题了？如果可以的话推荐用 CTRubyAnnotation。
如果实在想用的话可以直接用 Xcode 生成的 Objective-C Header。
